apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end-app
  template:
    metadata:
      labels:
        app: front-end-app
    spec:
      containers:
        - name: my-front-end-app
          image: public.ecr.aws/k8y9t4s7/frontend-group:22
          ports:
            - containerPort: 5173
