apiVersion: v1
kind: Service
metadata:
  name: my-service-frontend-app
spec:
  selector:
    app: front-end-app
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer
